sonar.projectKey=fsa-lab-app
sonar.projectName=FSA Lab App
sonar.projectVersion=1.0

sonar.sources=auth/src,import/src,export/src,db-service/src,email/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.test.inclusions=**/*.test.ts
sonar.coverage.exclusions=**/*.test.ts

sonar.javascript.lcov.reportPaths=\
  auth/coverage/lcov.info,\
  import/coverage/lcov.info,\
  export/coverage/lcov.info,\
  db-service/coverage/lcov.info,\
  email/coverage/lcov.info

sonar.typescript.tsconfigPaths=\
  auth/tsconfig.json,\
  import/tsconfig.json,\
  export/tsconfig.json,\
  db-service/tsconfig.json,\
  email/tsconfig.json
